Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'ticket_id': '04031153', 'passes_count': 6, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'ticket_id': '04031153', 'passes_count': 7, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'ticket_id': '04031153', 'passes_count': 8, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Exception on / [POST]
Traceback (most recent call last):
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ticket_scanner/app/main.py", line 130, in index
    anket_data = get_anket_data(visitor.id)
  File "ticket_scanner/app/main.py", line 83, in get_anket_data
    get_or_create_summit_attend(anket_id)
  File "ticket_scanner/app/main.py", line 46, in get_or_create_summit_attend
    attend = db.session.query(SummitAttend).join(SummitAnket).filter(
NameError: name 'SummitAttend' is not defined
Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Exception on / [POST]
Traceback (most recent call last):
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ticket_scanner/app/main.py", line 130, in index
    anket_data = get_anket_data(visitor.id)
  File "ticket_scanner/app/main.py", line 83, in get_anket_data
    get_or_create_summit_attend(anket_id)
  File "ticket_scanner/app/main.py", line 55, in get_or_create_summit_attend
    db.engine.execute(create)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
TypeError: 'dict' object does not support indexing
Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Exception on / [POST]
Traceback (most recent call last):
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ticket_scanner/app/main.py", line 130, in index
    anket_data = get_anket_data(visitor.id)
  File "ticket_scanner/app/main.py", line 83, in get_anket_data
    get_or_create_summit_attend(anket_id)
  File "ticket_scanner/app/main.py", line 54, in get_or_create_summit_attend
    """ % summit_id
NameError: name 'summit_id' is not defined
Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Exception on / [POST]
Traceback (most recent call last):
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (145993, 2017-11-27, 31153, null, 11:01:45.31348, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "ticket_scanner/app/main.py", line 130, in index
    anket_data = get_anket_data(visitor.id)
  File "ticket_scanner/app/main.py", line 83, in get_anket_data
    get_or_create_summit_attend(anket_id)
  File "ticket_scanner/app/main.py", line 55, in get_or_create_summit_attend
    db.engine.execute(create)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2064, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/rost/.virtualenvs/vocrm/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) null value in column "status" violates not-null constraint
DETAIL:  Failing row contains (145993, 2017-11-27, 31153, null, 11:01:45.31348, null).
 [SQL: 'INSERT INTO summit_summitattend\n                    (anket_id, date, time)\n                    VALUES\n                    (31153, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\n        ']
Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'passes_count': 13, 'visitor_id': 31153, 'ticket_id': '04031153', 'active': True, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg'}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'passes_count': 14, 'visitor_id': 31153, 'ticket_id': '04031153', 'active': True, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg'}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'passes_count': 15, 'ticket_id': '04031153', 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'visitor_id': 31153, 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'active': True, 'fullname': 'Сопилко Виктор Григорьевич', 'passes_count': 16, 'ticket_id': '04031153'}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'visitor_id': 31153, 'active': True, 'ticket_id': '04031153', 'passes_count': 17, 'fullname': 'Сопилко Виктор Григорьевич', 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg'}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153, 'fullname': 'Сопилко Виктор Григорьевич', 'ticket_id': '04031153', 'passes_count': 18}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': False, 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153, 'fullname': 'Сопилко Виктор Григорьевич', 'ticket_id': '04031153', 'passes_count': 18}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': False, 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153, 'fullname': 'Сопилко Виктор Григорьевич', 'ticket_id': '04031153', 'passes_count': 18}
<< Finish >>. Send response.


Received data from Form: Code: 04031153. Summit_id: 9
Calculated visitor with id = 31153
Calculated summit visitors data: {'active': True, 'profile_image': 'https://vocrm.net/media/images/blob_BepubnA.jpg', 'visitor_id': 31153, 'fullname': 'Сопилко Виктор Григорьевич', 'ticket_id': '04031153', 'passes_count': 19}
<< Finish >>. Send response.


Received data from Form: Code: fdgd. Summit_id: 9
Anket not found - 404.

